import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DevTools } from "@/components/dev/DevTools";
import { ClickToComponentClient } from "@/components/dev/ClickToComponentClient";
import { Web3Provider } from "@/providers/Web3Provider";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";
import { config } from "@/lib/wagmi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Obtener estado inicial de Wagmi desde las cookies (SSR)
  // Esto evita el "flash" de desconexión y errores de hidratación
  const initialState = cookieToInitialState(config, (await headers()).get("cookie"));

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased debug-ui`}
      >
        <Web3Provider initialState={initialState}>
          <ClickToComponentClient />
          {children}
          <DevTools />
        </Web3Provider>
      </body>
    </html>
  );
}
